CREATE TABLE Pupils (
    Id INT PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(MAX) NOT NULL,
    LastName NVARCHAR(MAX) NOT NULL,
    Gender NVARCHAR(MAX) NOT NULL,
    Grade NVARCHAR(MAX) NOT NULL
);

CREATE TABLE Teachers (
    Id INT PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(MAX) NOT NULL,
    LastName NVARCHAR(MAX) NOT NULL,
    Gender NVARCHAR(MAX) NOT NULL,
    Subject NVARCHAR(MAX) NOT NULL
);

CREATE TABLE PupilTeacher (
    PupilsId INT NOT NULL,
    TeachersId INT NOT NULL,
    PRIMARY KEY (PupilsId, TeachersId),
    FOREIGN KEY (PupilsId) REFERENCES Pupils(Id) ON DELETE CASCADE,
    FOREIGN KEY (TeachersId) REFERENCES Teachers(Id) ON DELETE CASCADE
);

CREATE INDEX IX_PupilTeacher_TeachersId ON PupilTeacher (TeachersId);
